name: e2e-test

on:
  push:
    paths-ignore:
      - "**.md"
  schedule:
    # UTC の 01:00 は JST だと 10:00 。
    # 1-5 で 月曜日から金曜日
    - cron: "0 1 * * 1-5"

env:
  TEST_SIGNALING_URLS: ${{ secrets.TEST_SIGNALING_URLS }}
  TEST_CHANNEL_ID_PREFIX: ${{ secrets.TEST_CHANNEL_ID_PREFIX }}
  TEST_SECRET_KEY: ${{ secrets.TEST_SECRET_KEY }}
  OPENH264_VERSION: 2.6.0

jobs:
  e2e_test_ubuntu:
    strategy:
      matrix:
        # mediapipe が Python 3.13 以降に対応していない
        # python_version: ["3.11", "3.12", "3.13", "3.14"]
        python_version: ["3.11", "3.12"]
        os: ["ubuntu-22.04", "ubuntu-24.04"]
    runs-on: ${{ matrix.os}}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v5
      # libx11-dev は Ubuntu 24.04 の時に必要になる模様
      - run: |
          sudo apt-get update
          sudo apt-get -y install libva2 libdrm2 libva-dev libdrm-dev libx11-dev portaudio19-dev
      - uses: shiguredo/github-actions/.github/actions/download-openh264@main
        id: openh264
        with:
          platform_name: ${{ matrix.os }}_x86_64
          openh264_version: ${{ env.OPENH264_VERSION }}
      - run: echo "OPENH264_PATH=${{ steps.openh264.outputs.openh264_path }}" >> $GITHUB_ENV
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python_version }}
      - run: uv sync
      - run: uv run pytest -v

  e2e_test_ubuntu_arm:
    strategy:
      matrix:
        # arm64 は Ubuntu-24.04 と Python 3.12 のみ対応
        python_version: ["3.12"]
        os: ["ubuntu-24.04-arm"]
    runs-on: ${{ matrix.os}}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v5
      # libx11-dev は Ubuntu 24.04 の時に必要になる模様
      - run: |
          sudo apt-get update
          sudo apt-get -y install libva2 libdrm2 libva-dev libdrm-dev libx11-dev portaudio19-dev
      - uses: shiguredo/github-actions/.github/actions/download-openh264@main
        id: openh264
        with:
          platform_name: ubuntu-24.04_arm64
          openh264_version: ${{ env.OPENH264_VERSION }}
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python_version }}
      - run: uv sync
      - run: uv run pytest -s
        env:
          OPENH264_PATH: ${{ steps.openh264.outputs.openh264_path }}

  e2e_test_macos:
    strategy:
      matrix:
        # mediapipe が Python 3.13 に対応していない
        # python_version: ["3.11", "3.12", "3.13"]
        python_version: ["3.11", "3.12"]
        # macos-13 は test_macos.py が上手くテストが動かないのでスキップ
        os: ["macos-14", "macos-15"]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v5
      - uses: shiguredo/github-actions/.github/actions/download-openh264@main
        id: openh264
        with:
          platform_name: macos_arm64
          openh264_version: ${{ env.OPENH264_VERSION }}
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python_version }}
      - run: uv sync
      - run: uv run pytest -s
        env:
          OPENH264_PATH: ${{ steps.openh264.outputs.openh264_path }}

  e2e_test_windows:
    strategy:
      matrix:
        # mediapipe が Python 3.13 に対応していない
        # python_version: ["3.11", "3.12", "3.13"]
        python_version: ["3.11", "3.12"]
    runs-on: windows-2022
    timeout-minutes: 15
    env:
      # Python を強制的に UTF-8 で利用するおまじない
      PYTHONUTF8: 1
    steps:
      - uses: actions/checkout@v5
      - uses: shiguredo/github-actions/.github/actions/download-openh264@main
        id: openh264
        with:
          platform_name: windows_x86_64
          openh264_version: ${{ env.OPENH264_VERSION }}
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python_version }}
      - run: uv sync
      - run: uv run pytest -s
        env:
          OPENH264_PATH: ${{ steps.openh264.outputs.openh264_path }}

  slack_notify_failed:
    needs:
      [e2e_test_ubuntu, e2e_test_ubuntu_arm, e2e_test_macos, e2e_test_windows]
    runs-on: ubuntu-24.04
    if: failure()
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: sora-python-sdk
          SLACK_COLOR: danger
          SLACK_TITLE: "FAILED"
          SLACK_ICON_EMOJI: ":japanese_ogre:"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
